clear first;
clear second;
incr second;
clear n;
while n not 20 do;
    clear fib;
    incr n;
    while fib not first do;
        incr fib;
    end;
    clear first;
    while first not second do;
        incr fib;
        incr first;
    end;
    while second not fib do;
        incr second;
    end;
end;